[tool.ruff]
line-length = 88
select = ["E", "F", "W", "I", "B", "C", "N", "D", "S", "T", "Q"]
ignore = []

[tool.black]
line-length = 88
target-version = ['py310']

[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true

[tool.pytest.ini_options]
python_files = "test_*.py"
testpaths = ["tests"]
addopts = "--cov=src --cov-report=term-missing"
