name: CI

on:
  push:
    branches: [ "main", "Task1-Foundation", "Task2-Data-Contracts", "Task3-Volatility-Models", "Task4-DCC-CVaR", "Task5-Backtesting", "Task6-Dashboard" ]
  pull_request:
    branches: [ "main", "Task1-Foundation", "Task2-Data-Contracts", "Task3-Volatility-Models", "Task4-DCC-CVaR", "Task5-Backtesting", "Task6-Dashboard" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff black mypy
    - name: Lint with ruff
      run: ruff check .
    - name: Check formatting with black
      run: black --check .

  type:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mypy
    - name: Type check with mypy
      run: mypy src

  test:
    runs-on: ubuntu-latest
    needs: type
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        pip install -e .
    - name: Test with pytest
      run: pytest -v --cov=src --cov-report=xml
    - name: Upload coverage
      uses: codecov/codecov-action@v3
